"""Data loading utilities for microbiome datasets."""

import os

import pandas as pd

from .synthetic import generate_synthetic_cohort


def load_cohort(name="synthetic", data_dir="data/raw", **kwargs):
    """Unified entry point for loading a microbiome cohort.

    Returns a consistent triple of (otu_df, metadata_df, taxonomy_df)
    regardless of the data source.

    Args:
        name: One of 'synthetic', 'hmp', 'agp', 'curatedmgd'.
        data_dir: Root data directory for real datasets.
        **kwargs: Passed to the underlying loader (e.g. seed, n_samples
            for synthetic, or body_site filtering for HMP).

    Returns:
        Tuple of (otu_df, metadata_df, taxonomy_df).
    """
    if name == "synthetic":
        return generate_synthetic_cohort(**kwargs)

    if name == "hmp":
        otu_df, metadata = load_hmp(os.path.join(data_dir, "hmp"))
        taxonomy = load_taxonomy(data_dir, dataset="hmp")
        return otu_df, metadata, taxonomy

    if name == "agp":
        otu_df, metadata = load_agp(os.path.join(data_dir, "agp"))
        taxonomy = load_taxonomy(data_dir, dataset="agp")
        return otu_df, metadata, taxonomy

    if name == "curatedmgd":
        otu_df, metadata = load_curated_mgd(os.path.join(data_dir, "curatedmgd"))
        taxonomy = load_taxonomy(data_dir, dataset="curatedmgd")
        return otu_df, metadata, taxonomy

    if name == "ibdmdb":
        from .ibdmdb_loader import load_ibdmdb
        abundance_df, metadata = load_ibdmdb(os.path.join(data_dir, "ibdmdb"))
        taxonomy = _parse_metaphlan_taxonomy(abundance_df.columns)
        return abundance_df, metadata, taxonomy

    raise ValueError(
        f"Unknown cohort: {name}. Use 'synthetic', 'hmp', 'agp', 'curatedmgd', or 'ibdmdb'."
    )


def load_hmp(data_dir="data/raw/hmp"):
    """Load HMP Phase 1 OTU table and metadata.

    Supports two formats:
    - TSV from r_scripts/download_hmp_bioconductor.R (recommended)
    - BIOM from legacy download script

    Args:
        data_dir: Path to the HMP raw data directory.

    Returns:
        Tuple of (otu_df, metadata_df). otu_df is samples x OTUs.
    """
    tsv_path = os.path.join(data_dir, "hmp1_otu_table.tsv")
    biom_path = os.path.join(data_dir, "hmp1_otu_table.biom")
    meta_path = os.path.join(data_dir, "hmp1_metadata.tsv")

    if os.path.exists(tsv_path):
        otu_df = pd.read_csv(tsv_path, sep="\t", index_col=0)
    elif os.path.exists(biom_path):
        from biom import load_table
        from .preprocess import biom_to_dataframe
        table = load_table(biom_path)
        otu_df = biom_to_dataframe(table)
    else:
        raise FileNotFoundError(
            f"No HMP OTU table found in {data_dir}. "
            "Run: Rscript r_scripts/download_hmp_bioconductor.R"
        )

    metadata = pd.read_csv(meta_path, sep="\t", index_col=0)
    return otu_df, metadata


def load_agp(data_dir="data/raw/agp"):
    """Load American Gut Project OTU table and metadata.

    Args:
        data_dir: Path to the AGP raw data directory.

    Returns:
        Tuple of (otu_df, metadata_df).
    """
    from biom import load_table
    from .preprocess import biom_to_dataframe

    biom_path = os.path.join(data_dir, "agp_otu_table.biom")
    meta_path = os.path.join(data_dir, "agp_metadata.tsv")

    table = load_table(biom_path)
    otu_df = biom_to_dataframe(table)

    metadata = pd.read_csv(meta_path, sep="\t", index_col=0)

    return otu_df, metadata


def load_curated_mgd(data_dir="data/raw/curatedmgd"):
    """Load curatedMetagenomicData exports (generated by R script).

    The R script exports abundance tables and metadata as TSV files.
    Multiple studies are concatenated with a 'study_name' column in metadata.

    Args:
        data_dir: Path to the curatedMetagenomicData export directory.

    Returns:
        Tuple of (abundance_df, metadata_df).
    """
    abundance_path = os.path.join(data_dir, "curated_abundance.tsv")
    meta_path = os.path.join(data_dir, "curated_metadata.tsv")

    if not os.path.exists(abundance_path):
        raise FileNotFoundError(
            f"curatedMetagenomicData export not found at {abundance_path}. "
            "Run: Rscript scripts/download_curatedmgd.R"
        )

    abundance = pd.read_csv(abundance_path, sep="\t", index_col=0)
    metadata = pd.read_csv(meta_path, sep="\t", index_col=0)

    return abundance, metadata


def load_taxonomy(data_dir="data/raw", dataset="hmp"):
    """Load or construct taxonomy table for a dataset.

    For HMP/AGP, taxonomy is extracted from OTU IDs or observation metadata.
    For curatedMetagenomicData, taxonomy is embedded in species names.

    Args:
        data_dir: Path to data root.
        dataset: One of 'hmp', 'agp', 'curatedmgd'.

    Returns:
        pd.DataFrame with columns: Kingdom, Phylum, Class, Order, Family, Genus, Species.
    """
    tax_path = os.path.join(data_dir, dataset, "taxonomy.tsv")

    if os.path.exists(tax_path):
        return pd.read_csv(tax_path, sep="\t", index_col=0)

    # For curatedMetagenomicData, parse species-level names
    if dataset == "curatedmgd":
        abundance_path = os.path.join(data_dir, "curatedmgd", "curated_abundance.tsv")
        if os.path.exists(abundance_path):
            abundance = pd.read_csv(abundance_path, sep="\t", index_col=0)
            return _parse_metaphlan_taxonomy(abundance.columns)

    raise FileNotFoundError(
        f"Taxonomy file not found at {tax_path}. "
        "Generate it using the preprocessing pipeline."
    )


def _parse_metaphlan_taxonomy(species_names):
    """Parse MetaPhlAn-style taxonomy strings into a DataFrame.

    E.g. 'k__Bacteria|p__Firmicutes|...|s__Faecalibacterium_prausnitzii'

    Args:
        species_names: Iterable of taxonomy strings.

    Returns:
        pd.DataFrame with taxonomy columns.
    """
    levels = ["Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"]
    prefixes = ["k__", "p__", "c__", "o__", "f__", "g__", "s__"]

    records = []
    for name in species_names:
        parts = str(name).split("|")
        row = {}
        for level, prefix in zip(levels, prefixes):
            match = [p.replace(prefix, "") for p in parts if p.startswith(prefix)]
            row[level] = match[0] if match else ""
        row["feature_id"] = name
        records.append(row)

    df = pd.DataFrame(records).set_index("feature_id")
    return df
